Add TM stats e
hotosm/osm-stats-api pull request #155
Opened 2022-02-17 14:57 UTC by d-rita

2022-03-02 12:30 UTC, itskshitiz321 reviewed
Code Wise all good from my side ! Will test it with endpoint itself and leave comment if found any

2022-03-02 12:30 UTC, itskshitiz321 commented on tests/src/test_app.py
> +    print(result_time_spent_mapping_and_validating_query.encode('utf-8'))
Avoid Printing test queries !

2022-03-02 12:30 UTC, itskshitiz321 commented on tests/src/test_app.py
> +    print(result_tasks_mapped__and_validated_query.encode('utf-8'))
Same here as well

2022-03-03 06:38 UTC, itskshitiz321 commented
It is expected that this PR should resolve this issue as well 

- Resolve #115

2022-03-14 11:28 UTC, itskshitiz321 requested changes
API breakdowns with multiple combination of input supported for Mapathon detailed report !

2022-03-14 11:28 UTC, itskshitiz321 commented on src/galaxy/query_builder/builder.py
> +    project_ids = ",".join([str(p) for p in params.project_ids])
We have several conditions for Mapathon Reports , For eg: Project ID can be empty it is optional field user may can only supply hashtag or only project id , This generator will work for those cases where project id is supplied but will not work when hashtag is supplied , Here is the sample query output of this function 
```
        SELECT DISTINCT th.user_id,
            (
                SELECT COUNT(task_id)
                FROM public.task_history
                WHERE user_id = th.user_id
                AND action_text = 'MAPPED'
                AND action_date BETWEEN '2021-09-23 18:30:00' AND '2021-09-24 18:15:00'
                AND project_id IN ()
            ) AS mapped_task_count,
            (
                SELECT COUNT(task_id)
                FROM public.task_history
                WHERE user_id = th.user_id
                AND action_text = 'VALIDATED'
                AND action_date BETWEEN '2021-09-23 18:30:00' AND '2021-09-24 18:15:00'
                AND project_id IN ()
            ) AS validated_task_count
        FROM public.task_history th
        WHERE th.action_text = 'MAPPED' OR th.action_text = 'VALIDATED'
```

2022-03-14 11:28 UTC, itskshitiz321 commented on src/galaxy/query_builder/builder.py
> +def create_user_tasks_mapped_and_validated_query(params):
Similar condition here as well , new condition is needed for hashtags !

2022-03-14 11:28 UTC, itskshitiz321 commented on src/galaxy/query_builder/builder.py
> +def create_user_tasks_mapped_and_validated_query(params):
You can Checkout validation models for input fields !

2022-03-22 13:44 UTC, omranlm approved these changes
Reviewed the queries to get tasks mapped and validated and they match what we had in the insights before

2022-03-28 16:50 UTC, itskshitiz321 approved these changes

2022-04-04 15:10 UTC, merged